### ISSUE TITLE
fail to start the systemd service due to the "test" utility being only in /usr/bin

### ISSUE THREAD

**Issue by vinc17fr** [philfry/ocsp_proxy#2]
In `ocsp_proxy.service`:

    ExecStartPre=/bin/test -S $redis_sock -a -r $redis_sock

but on Debian machines, the "test" utility is only in /usr/bin, so that the service cannot be started. Shouldn't `/bin/test` be replaced by just `test`?

**Comment by philfry** [comment]
Hi,

as some distributions like RHEL7 ship a pretty old version of systemd that does not support non-absolute paths for `Exec` yet (see https://github.com/systemd/systemd/commit/5008da1ec1cf2cf8c15b702c4052e3a49583095d), unfortunately there's no general solution for this.
Looks like Debian is also [making efforts](https://wiki.debian.org/UsrMerge) to consolidate `usr/s?bin` and `s?bin`.

**Comment by vinc17fr** [comment]
How about checking the location of `test`, then modify `ocsp_proxy.service` in `Makefile` as already done for the path to `ocsp_proxy`?

**Comment by philfry** [comment]
Thanks for your input! Your issue should be fixed in head; if not, please feel free to reopen this issue.
